### PR TITLE
Docs updates

### PR DESCRIPTION
**Pull request by ralphpeterson**
Some basic docs updates to make installation instructions more clear for novice python users (#96). Still needs some work.

1.) @NickleDave can you please add instructions for installing with "pure Python environment"?
2.) @NickleDave can you please confirm which version of Python the repo depends on?

### CODE REVIEW

**Comment by NickleDave** [comment]
Thanks so much @ralphpeterson for taking care of this.

> 1.) @NickleDave can you please add instructions for installing with "pure Python environment"?
> 2.) @NickleDave can you please confirm which version of Python the repo depends on?

I added the following:
- A section with the single command, for people that already uderstand envs etc. and just want a single thing to copy-paste into their terminal
- A section below that with what you added (thank you!) as well as the "pure Python" commands
- I added an "admonition" that explains which versions of Python that VocalPy will work with. The short answer is that right now we require `python>=3.9`. The longer answer is that I realized we should drop 3.9, see #102. For the conda commands, I changed to `python=3.11`. Annoyingly, this can go stale, but at the moment I don't want to deal with automating a check for that.

I also made some other changes while I was at it. You don't need to review this but if you have comments I'm happy to hear them.

I just want to make the landing page less verbose and also restructure the docs as per [The Grand Unified Theory of Documentation](https://documentation.divio.com/). Basically I am copying the style of of the [numpy docs](https://numpy.org/doc/stable/index.html) and [scipy docs](https://docs.scipy.org/doc/scipy/). Hopefully not in such a way that my PhD will be revoked for plagiarism. To achieve this I revamped the front page and moved other material around. The "user guide" is basically wishful thinking right now, I will raise an issue with what sections I think should be there; we can edit that as we figure it out more.
Note that the link to the contributing guide is also broken, will be fixed in #101 

Build is here on readthedocs: 
https://vocalpy--99.org.readthedocs.build/en/99/
Page you revised:
https://vocalpy--99.org.readthedocs.build/en/99/getting_started/installation.html

**Comment by NickleDave** [comment]
@all-contributors please add @ralphpeterson for documentation

**Comment by ralphpeterson** [comment]
looks great!

**Comment by NickleDave** [comment]
Excellent, thanks again for your help

**Pull request merged**
